@echo off

:: Run CMake, we want output to be a makefile for MinGW
echo [32mRunning CMake...[0m
cmake -S env -B build -G "MinGW Makefiles"

:: Run make with files generated by CMake
echo [32mRunning make...[0m
cd build
mingw32-make.exe
cd ..

:: That's it!
echo [32mDone![0m
PAUSE

@echo on